# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: '麦田男孩'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ryeboy.org" # the base hostname & protocol for your site
copyright: "© Copyright 2013-2015 Fuzhou Ryesun Culture Communication Co., Ltd."

# Build settings
markdown: kramdown
