# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: '麦田男孩APP官方网站'
description: '麦田男孩是公益健康习惯平台,专业APP,超过100多位义工,科学运动和完整计划,助你养成良好生活习惯'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ryeboy.org" # the base hostname & protocol for your site
copyright: "<a href='http://www.beian.miit.gov.cn' target='_blank'>闽ICP备15011069号</a>"

# Build settings
markdown: kramdown
